Default: &defaults
  database: katan.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: katan_test.sqlite3
  <<: *defaults

Staging:
  database: katan_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: katan_production.sqlite3
  poolsize: 100
  <<: *defaults
